FROM python:alpine

LABEL io.whalebrew.name 'formica'
LABEL io.whalebrew.config.environment '["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_DEFAULT_REGION"]'
LABEL io.whalebrew.config.volumes '["~/.aws:/.aws"]'
ENTRYPOINT ["formica"]

RUN apk add --no-cache groff less mailcap

WORKDIR /app

COPY ./ ./

RUN pip install .