Resources:
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
        - ''
        - - "/aws/lambda/"
          - Ref: StepFunctionLambdaFunction
  StepFunctionLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: "{{ code('code.py') }}"
      Handler: index.handler
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Runtime: python2.7
